### ISSUE TITLE
install error in linux with gd-utils

### ISSUE THREAD

**Issue by Sirfrancis18** [roshanconnor123/Gdutils_Tgbot#4]
hi
i install gd-utils in linux . when i execute sh the program throw this error
```
internal/modules/cjs/loader.js:895
  throw err;
  ^

Error: Cannot find module '/root/count'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
i install in `/datos/gd-utils` (folder)

**Comment by roshanconnor123** [comment]
I see
then u have to edit the sh file and replace all `~gd-utils` part with `/datos/gd-utils`

**Comment by Sirfrancis18** [comment]
i changed cd ~ && cd gd-utils
c /datos && cd gd-utils
same error 
Error: Cannot find module '/root/count'
